//@version=6
// Need a Custom Script Developed? Contact Me = sales@byeol.tech or https://byeol.tech/#contact

indicator('Kairi Relative Index with Arrows', shorttitle = 'KRI with Arrows')

length = input.int(title = 'Length', defval = 14, minval = 1)
src = input(title = 'Source', defval = close)

sma = ta.sma(src, length)
kri = 100 * (src - sma) / sma

kriColor = kri >= 0 ? #0ebb23 : color.red


// Buy/Sell signals
buySignal = ta.crossover(kri, 0)
sellSignal = ta.crossunder(kri, 0)

plotshape(buySignal, title = 'Buy', style = shape.triangleup, color = color.new(color.green, 0), location = location.belowbar, size = size.small)
plotshape(sellSignal, title = 'Sell', style = shape.triangledown, color = color.new(color.red, 0), location = location.abovebar, size = size.small)
